### ISSUE TITLE
Awesome project!

### ISSUE THREAD

**Issue by Urigo** [danstarns/idio-graphql#2]
Hi @danstarns !

Really cool project!
From skimming a bit through the source code, it seems that maybe it would be possible to reuse some functionality from https://github.com/ardatan/graphql-toolkit ?

Things like [schema loading](https://github.com/ardatan/graphql-toolkit#schema-loading), [merging](https://github.com/ardatan/graphql-toolkit#epoxy) and some [other utils](https://github.com/ardatan/graphql-toolkit#other-utils) maybe?

I would love to work together and contribute if that seems interesting for you?

**Comment by danstarns** [comment]
Hey @Urigo , 

Glad you like it :) Thanks for the link! I'll have a look through and see how functionality could be applied. Id love to work with you & other community members to make the project better, Pull requests & suggestions are welcome :)

**Comment by danstarns** [comment]
Thanks for your suggestion, I had a dig around & found 2 methods, `printWithComments` & `mergeTypeDefs`  that have helped inspire changes in [version 2.0](https://github.com/danstarns/idio-graphql/blob/master/changelog/2.0.md). I'll mark this as closed & any more suggestions or collaboration is welcome :) 🍻
